cpus = 1
memory = 1024
[zyx]
[containerLand]
    cpus = 2
    memory = "2048"
#    cloud_config = "examples/cloud-init/docker-only-with-persistent-storage.txt"
#    create volume bellow w/ "qcow-tool create --size=16GiB var_lib_docker.img.qcow2"
#    volume = "var_lib_docker.img.qcow2"
[xpto]
    channel = stable
